version : '3'

services: 
  
  servidordb:
    image: mariadb:10.7.1
    volumes:
      - ./db:/var/lib/mysql
      - ./db_config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=bjsnwe08
    ports:
      - 3333:3306
